# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YqOMtx_rYTxEwVqXL4wXyLt1zTPHSHEa
"""

# Step 1: Import Libraries
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np


# Step 2: Load the CIFAR-10 Dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()


# Step 3: Define Class Names
class_names = [
'airplane','automobile','bird','cat','deer',
'dog','frog','horse','ship','truck'
]


# Step 4: Visualize a Sample Image
plt.imshow(x_train[0])
plt.title(class_names[y_train[0][0]])
plt.show()


# Step 5: Normalize Pixel Values
x_train = x_train / 255.0
x_test = x_test / 255.0


# Step 6: Build the CNN Model
model = models.Sequential()

# First Convolution Layer
model.add(layers.Conv2D(32,(3,3),activation='relu',input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))

# Second Convolution Layer
model.add(layers.Conv2D(64,(3,3),activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

# Third Convolution Layer
model.add(layers.Conv2D(64,(3,3),activation='relu'))

# Flatten Layer
model.add(layers.Flatten())

# Dense Layers
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(10,activation='softmax'))


# Step 7: Compile the Model
model.compile(
optimizer='adam',
loss='sparse_categorical_crossentropy',
metrics=['accuracy']
)


# Step 8: Train the Model
model.fit(
x_train,
y_train,
epochs=10,
validation_data=(x_test,y_test)
)


# Step 9: Evaluate the Model
test_loss, test_acc = model.evaluate(x_test,y_test)

print("Test Accuracy:",test_acc)


# Step 10: Make Predictions
predictions = model.predict(x_test)

# Example Prediction
print("Predicted Class:", class_names[np.argmax(predictions[0])])
print("Actual Class:", class_names[y_test[0][0]])